---
functional:
  - Пользователь должен иметь возможность выбрать игру по уровню сложности
  - Пользователь должен иметь возможность выбрать язык программирования в редакторе код
  - Пользователь должен иметь возможность перевести задачу на один из двух языков — русский и английский
  - При завершении игры должно высвечиваться модальное окно с информацией о победителе игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
implicit:
  - Нажатие на логотип сайта должно вести на главную страницу сайта
  - Пользователь должен иметь возможность сортировать рейтинг пользователей по заданным критериям
  - Пользователь должен иметь возможность просматривать профили других игроков
